env: "dev"

database:
  host: "pr_postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "pullrequest"
  sslmode: "disable"

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s