env: "local"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "questions"
  sslmode: "disable"
  seed: true
  migration_path: "internal/infrastructure/storage/postgres/migrations"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
